# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eKactgUbnbYdhlRJZqzPu-egBYfAiKXZ
"""
import re
import string
from flask import Flask,jsonify,request
from flask_cors import CORS
from sklearn.feature_extraction.text import TfidfVectorizer

def text_preproc(x):
  #case folding
  x = x.lower()
  #remove url
  x = re.sub(r'https*\S+', ' ', x)
  #remove username
  x = re.sub(r'<username>\s+', ' ', x)
  #remove punctuation
  x = re.sub('[%s]' % re.escape(string.punctuation), ' ', x)
  #remove number
  x = re.sub(r'\d', '', x)
  #remove double space
  x = re.sub(r'\s{2,}', ' ', x)
  return x

app = Flask(__name__)

@app.route('/')
def index():
    return "<h1>Welcome to our server !!</h1>"

if __name__ == '__main__':
    # Threaded option to enable multiple instances for multiple user access support
    app.run(threaded=True, port=5000)