# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eKactgUbnbYdhlRJZqzPu-egBYfAiKXZ
"""

app = Flask(__name__)
CORS(app)

@app.route('/')
def home():
    return 'Hello World'

if __name__=='__main__':
    app.run()